# This is a definition file for GitLab CI.

default:
  #image: "archlinux/base"
  image: "debian:stable"
  timeout: 300m

build_A:
  stage: build
  needs: []
  before_script:
    # Arch Linux.
    #- "cp -R ./docker/build_bases/arch /scratch_base"
    #- "cp -R ./docker/builders/arch /scratch"
    #- "cp -R . /dcma"
    # CI.
    - "cp -R ./docker/builders/ci /scratch"
    - "cp -R . /dcma"

  script:
    # Arch Linux.
    #- "/scratch_base/implementation_arch.sh"
    #- "/scratch/implementation_arch.sh"
    # CI.
    - |
      ( ( while true ; do sleep 225 ; printf '\n\n' ; df -h ; printf '\n' ; free -h ; printf '\n\n' ; done ) &)
      "/scratch/implementation_ci_debian_stable.sh"

#  artifacts:
#    paths:
#      - mybinary
#      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
#      # cache:
#      #   paths:
#      #     - "*.o"

test_A:
  stage: test
  needs: ["build_A"]
  script:
    # Ensure the default run script works correctly.
    - "./integration_tests/Run.sh"

deploy_A:
  stage: deploy
  needs: ["test_A"]
  script:
    - "echo 'Deployment placeholder successful'"
    # Extract an AppImage from the container.
    #- "./docker/scripts/ci/Extract_AppImage.sh"

