
# This config file facilitates automated static analysis on lgtm.com.
path_classifiers:
  test:
    - exclude: /
    # Note: the following require a preceeding `shopt -s dotglob`.
    - "src/**/*.cc"
    - "src/**/*.h"

extraction:
  cpp:
    prepare:
      packages:
      # Explicitly install known packages.
      - "git"
      - "cmake"
      - "make"
      - "g++"
      - "vim"
      - "ncurses-term"
      - "gdb"
      - "rsync"
      - "wget"
      - "ca-certificates"
      - "libgsl-dev"
      - "libeigen3-dev"
      - "libboost-dev"
      - "libboost-filesystem-dev"
      - "libboost-iostreams-dev"
      - "libboost-program-options-dev"
      - "libboost-thread-dev"
      - "libz-dev"
      - "libsfml-dev"
      - "libjansson-dev"
      - "libpqxx-dev"
      - "libcgal-dev"
      - "libnlopt-dev"
      - "libnlopt-cxx0"
      - "libasio-dev"
      - "freeglut3-dev"
      - "libxi-dev"
      - "libxmu-dev"
      - "xorg-dev"
      - "xserver-xorg-dev"
      - "mesa-common-dev"
    after_prepare:
    # Create an accessible installation root directory.
    - "cd $LGTM_WORKSPACE"
    - "mkdir -pv placeholder_root/{include,lib,bin,share}"
    # Ygor.
    - "cd $LGTM_WORKSPACE"
    - "mkdir -pv ygor"
    - "cd ygor"
    - "git clone https://github.com/hdclark/ygor ."
    - "CXXFLAGS=-I$LGTM_WORKSPACE/placeholder_root/include LDFLAGS=-L$LGTM_WORKSPACE/placeholder_root/lib ./compile_and_install.sh -u -i $LGTM_WORKSPACE/placeholder_root -b build"
    # Explicator.
    - "cd $LGTM_WORKSPACE"
    - "mkdir -pv explicator"
    - "cd explicator"
    - "git clone https://github.com/hdclark/explicator ."
    - "CXXFLAGS=-I$LGTM_WORKSPACE/placeholder_root/include LDFLAGS=-L$LGTM_WORKSPACE/placeholder_root/lib ./compile_and_install.sh -u -i $LGTM_WORKSPACE/placeholder_root -b build"
    # YgorClustering.
    - "cd $LGTM_WORKSPACE"
    - "mkdir -pv ygorclustering"
    - "cd ygorclustering"
    - "git clone https://github.com/hdclark/ygorclustering ."
    - "CXXFLAGS=-I$LGTM_WORKSPACE/placeholder_root/include LDFLAGS=-L$LGTM_WORKSPACE/placeholder_root/lib ./compile_and_install.sh -u -i $LGTM_WORKSPACE/placeholder_root -b build"
    # Wt.
    - "cd $LGTM_WORKSPACE"
    - "mkdir -pv wt"
    - "cd wt"
    - "git clone https://github.com/emweb/wt.git ."
    - "mkdir -p build && cd build"
    - "cmake -DCMAKE_INSTALL_PREFIX='' ../"
    - "make -j 2 VERBOSE=1 DESTDIR=$LGTM_WORKSPACE/placeholder_root install"
    index:
      # Notes: 
      #  - built in-repo so analysis tooling picks up the source files.
      #  - have to remove .git to permit in-repo builds.
      #  - installed to exercise the install script, but only install to user-accessible location.
      build_command: "rm -rf .git && CXXFLAGS=-I$LGTM_WORKSPACE/placeholder_root/include LDFLAGS=-L$LGTM_WORKSPACE/placeholder_root/lib ./compile_and_install.sh -u -i $LGTM_WORKSPACE/placeholder_root -b $LGTM_SRC"

