language: cpp

services:
  - docker

before_install:
  - df -h .
  - free -h
  - sudo swapoff -a
  - sudo dd if=/dev/zero of=swapfile bs=1024 count=10GB
  - sudo mkswap swapfile
  - sudo swapon -a
  - |
    ( ( while true ; do sleep 225 ; printf '\n\n' ; free -h ; TERM=xterm top | head -n 20 ; printf '\n\n' ; done ) &)
    time sudo docker build -t dcma:latest -f docker/Dockerfile .
  - sudo docker ps -a

script:
  - time sudo docker run -it --rm -w /start/ dcma:latest dicomautomaton_dispatcher -h

after_failure:
  - free -h

