language: cpp

services:
  - docker

before_install:
  - df -h .
  - free -h
  - |
    ( ( while true ; do sleep 225 ; printf '\n\n' ; free -h ; printf '\n\n' ; done ) &)
    time sudo docker build --network=host -t dcma_ci:latest -f docker/builders/ci/Dockerfile .
  - sudo docker ps -a

script:
  - time sudo docker run -it --rm -w /start/ dcma_ci:latest dicomautomaton_dispatcher -h

after_failure:
  - free -h

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGhjbGFyayUzQW1hdHJpeC5vcmcvJTIxc3pRZGpKU2xuaVpBVHVWU3FwJTNBbWF0cml4Lm9yZw"
        on_success: always  # always|never|change
        on_failure: always
        on_start: never

