language: cpp

services:
  - docker

before_install:
  - df -h .
  - free -h
  - |
    ( ( while true ; do sleep 550 ; printf '\n\n' ; free -h ; top | head -n 20 ; printf '\n\n' ) &)
    time sudo docker build -t dcma:latest -f docker/Dockerfile .
  - sudo docker ps -a

script:
  - time sudo docker run -it --rm -w /start/ dcma:latest dicomautomaton_dispatcher -h

