language: cpp

services:
  - docker

before_install:
  - df -h .
  - free -h
  - |
    ( ( while true ; do sleep 225 ; printf '\n\n' ; free -h ; printf '\n\n' ; done ) &)
    ./docker/builders/ci/build.sh 
  - sudo docker ps -a

script:
  # Ensure the default run script works correctly.
  - ./docker/scripts/ci/Run_Container.sh
  # Extract an AppImage from the container.
  - ./docker/scripts/ci/Extract_AppImage.sh
  - mkdir -pv ci_artifacts
  - "mv DICOMautomaton*AppImage ci_artifacts/"

after_failure:
  - free -h

# Notify that the CI run finished.
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGhjbGFyayUzQW1hdHJpeC5vcmcvJTIxc3pRZGpKU2xuaVpBVHVWU3FwJTNBbWF0cml4Lm9yZw"
        on_success: always  # always|never|change
        on_failure: always
        on_start: never

## Upload the AppImage to GitHub Releases with tag 'continuous'.
##
## NOTE: deletes and re-creates the 'continuous' tag, which wreaks havoc for mirrors. :(
#after_success:
#  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
#  - bash upload.sh artifacts/DICOMautomaton*AppImage
#
#branches:
#  except:
#    - /^(?i:continuous)$/

# Upload the AppImage to a GitHub page.
deploy:
  - provider: pages:git
    edge: true
    repo: hdclark/hdclark.github.io
    target_branch: master
    keep_history: false
    local_dir: ci_artifacts
    cleanup: false
