language: cpp

services:
  - docker

before_install:
  - df -h .
  - free -h
  - |
    ( ( while true ; do sleep 225 ; printf '\n\n' ; free -h ; printf '\n\n' ; done ) &)
    ./docker/builders/ci/build.sh
  - sudo docker ps -a

script:
  - ./docker/scripts/ci/Run_Container.sh

after_failure:
  - free -h

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGhjbGFyayUzQW1hdHJpeC5vcmcvJTIxc3pRZGpKU2xuaVpBVHVWU3FwJTNBbWF0cml4Lm9yZw"
        on_success: always  # always|never|change
        on_failure: always
        on_start: never

