
# This script is used to enable and configure the GitLab web IDE.

terminal:
  image: "debian:stable"
  before_script:
    - "apt-get update"
  script:
    # Note: script must run long enough for web IDE to connect. The following is recommended.
    - "sleep 60"

